name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run go vet
        run: go vet .

      - name: Run go test
        run: go test -v -cover -vet=off .
